# docker-compose up
# open : http://localhost:8889

version: "3"
services:
  app:
    build: .
    # image: javid141/qqq
    container_name: springapp
    environment:
      DB_HOST: db
    ports:
      - 8889:8889
    restart: always
    depends_on:
      - db
  db:
    image: postgres:9.3
    container_name: db
    environment:
      - POSTGRES_USER=postgress
      - POSTGRES_PASSWORD=postgress
      - POSTGRES_DB=attsw
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
volumes:
  pgdata:
