version: "3"
services:
  db:
    image: postgres:9.3
    container_name: db
    environment:
      - POSTGRES_USER=postgress
      - POSTGRES_PASSWORD=postgress
      - POSTGRES_DB=attsw
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 127.0.0.1:5432:5432
    restart: unless-stopped
