server:
  port: 8889

spring:
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    properties:
      hibernate:
        default_schema: attsw
        jdbc:
          lob:
            non_contextual_creation: true
      hbm2ddl:
        auto: update
  database:
    driverClassName: "org.postgresql.Driver"
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/attsw?currentSchema=attsw
    username: postgres
    password: postgress
    hikari:
       maximumPoolSize: 2
       connectionTimeout: 60000
       idleTimeout: 600000
       maxLifetime: 1800000
  hibernate:
    hbm2ddl: update
