server:
  port: 8889

spring:
  jpa:
    show-sql: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/attsw?currentSchema=attsw
    username: postgress
    password: postgress
  hibernate:
    hbm2ddl: update
