server:
  port: 8889
spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # default_schema: attsw
        jdbc:
          lob:
            non_contextual_creation: true
      hbm2ddl:
        auto: create
  datasource:
    platform: postgres
    url: jdbc:postgresql://${DB_HOST}:5432/attsw
    username: postgress
    password: postgress
